#!/bin/bash
rm -rf final
mkdir final
cd final
cd ..
cp build/deceiver final
cp -R build/assets/ final/assets
cp build/gamecontrollerdb.txt final
cp .itch-linux.toml final/.itch.toml
cp build.txt final
cp shipme.txt final/readme.txt
