#!/bin/bash
set -e
set -o pipefail

sudo apt-get install clang lldb cmake make libx11-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxrandr-dev libxext-dev libxmu-dev libxinerama-dev libxcursor-dev blender libssl-dev libasound2-dev libpulse-dev
