#!/bin/bash
set -e
set -o pipefail

if which blender >/dev/null; then
    echo "Good news, Blender is set up correctly on the path!"
else
	echo "Please install Blender 2.75a or higher and make sure it's on the system path!"
    exit 1
fi

brew install cmake pkg-config
git submodule update --init --recursive
mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Debug
make
