#!/bin/bash
set -e
set -o pipefail

blender=0
if which blender >/dev/null; then
	blender_version="$(blender --version)"
	blender_version_extracted="${blender_version:8:4}"
	if (( $(echo "$blender_version_extracted > 2.75" | bc -l) )); then
		blender=1
		echo "Good news, Blender is set up correctly on the path!"
	fi
fi

if [ $blender -eq 0 ]; then
	echo "Please install Blender 2.75 or higher and make sure it is available on the path."
	exit 1
fi

git submodule update --init --recursive
mkdir -p build
cd build
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
cmake .. -DCMAKE_BUILD_TYPE=Debug -DSERVER=1 -DCLIENT=1
cpu_count=`cat /proc/cpuinfo | grep -i 'processor' | wc -l`
echo "Building with "$cpu_count" jobs"
make -j$cpu_count
