#!/bin/bash
set -e
set -o pipefail

if which blender >/dev/null; then
    # We have blender
else
	echo "Please install Blender and make sure it's on the system path!"
    exit 1
fi

brew install cmake pkg-config
git submodule update --init --recursive
mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Debug
make
