#!/bin/bash
set -e
set -o pipefail

if which blender >/dev/null; then
    echo "Good news, Blender is set up correctly on the path!"
else
	echo "Please install Blender 2.75a or higher and make sure it's on the system path!"
    exit 1
fi

sudo apt-get install clang lldb-3.5 cmake make libx11-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxrandr-dev libxext-dev libXmu-dev libxinerama-dev libxcursor-dev
git submodule update --init --recursive
mkdir -p build
cd build
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
cmake .. -DCMAKE_BUILD_TYPE=Debug
cpu_count=`cat /proc/cpuinfo | grep -i 'processor' | wc -l`
echo "Building with "$cpu_count" jobs"
make -j$cpu_count
