#!/bin/bash
cd "`dirname "$0"`"
cd ..
rm -rf final
mkdir -p final/LASERCRABS.app/Contents/MacOS
mkdir final/LASERCRABS.app/Contents/Resources
cp build/lasercrabs final/LASERCRABS.app/Contents/MacOS
cp -R build/assets/ final/LASERCRABS.app/Contents/MacOS/assets
cp build/gamecontrollerdb.txt final/LASERCRABS.app/Contents/MacOS
cp build/libsteam_api.dylib final/LASERCRABS.app/Contents/MacOS
cp ship/build.txt final/LASERCRABS.app/Contents/MacOS
cp ship/Info.plist final/LASERCRABS.app/Contents
cp ship/icon.icns final/LASERCRABS.app/Contents/Resources/icon.icns
cp ship/.itch-mac.toml final/.itch.toml
cp ship/shipme.txt final/readme.txt
cp ship/run-mac-linux final/LASERCRABS.app/Contents/MacOS/lasercrabs-launcher
cd ship
